language: cpp
compiler: gcc
dist: trusty
addons:
  apt:
    packages:
      - p7zip-full
script:
  - exit 0
# Build fails anyway. See explanation in
# https://github.com/ONLYOFFICE/core/pull/29#issuecomment-306773327
  - cd Common/3dParty && ./make.sh
  - cd ../../
  - make